version: "3.9"

networks:
    gotte-net:
        external: true

services:
    nginx:
        image: nginx:1.23.0
        container_name: www_nginx
        restart: unless-stopped
        ports:
            - 80:80
        environment:
            - NGINX_PORT=80
        volumes:
            - ./www:/usr/share/nginx/html
        networks:
            gotte-net:
                ipv4_address: 190.160.0.202